# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11b92937066117e1089d76e236fb979514b08288f7564cb2b3831d9a9d1f1ca826f000d083dfdf38899349d70c86459bd250031ad5c6e3f92496f6ee55f57c80

test:
  secret_key_base: 7ed3b6fc2ecdca486b1eb07b75b544a2143f2bd8c0accbb0a9aab9783185e9dc350c45c1ae010851b5f8b0cd019b263a797c5cbe52a12e82041670a6f0fa9ba3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
